import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import dynamic from 'next/dynamic';
import Hero from '@/components/Hero/Hero';
import Services from '@/components/services/Services';
import WhyChoose from '@/components/whyChoose/WhyChoose';
import Slider from '@/components/Slider/Slider';
import Footer from '@/components/footer/Footer';
import Counter from '@/components/counter/index.js';
const NavBar = dynamic(() => import('@/components/NavBar/NavBar'));
const BgImage = dynamic(() => import('@/components/bigImage/BgImage'));

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <main >
      <NavBar/>
      <Hero/>
      <Counter/>
      <Services/>
      <BgImage/>
      <WhyChoose/>
      <Slider/>
      <Footer/>
      </main>
    </>
  )
}
